version: "3.8"

services:
  listener-server:
    build: ./listener-server
    ports:
      - "7001:7001"
    volumes:
      - ./listener-server:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - receiver-server

  receiver-server:
    build: ./receiver-server
    ports:
      - "8001:8001"
    volumes:
      - ./receiver-server:/app
    environment:
      - NODE_ENV=production
