version: "3.8"

services:
  receiver-server:
    build: 
      context: ./receiver-server  
      dockerfile: Dockerfile.receiver    
    container_name: receiver-server
    ports:
      - "8001:8001"
    volumes:
      - ./receiver-server:/app
      - /app/node_modules
    command: npm run start

  listener-server:
    build: 
      context: ./listener-server 
      dockerfile: Dockerfile.listener    
    container_name: listener-server
    ports:
      - "7001:7001"
    volumes:
      - ./listener-server:/app
      - /app/node_modules
    command: npm run start
